<?php

/**
 * Implementation of hook_menu().
 */
function park_pages_menu() {
    
  $items = array();
  
  $items['home'] = array( 
      //'title' => t('Home'),
      'page callback' => 'park_pages_getHomePage',
      //'page arguments' => array(1, 'blog_post', 'blog post', 'blog posts'),
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    );

  return $items;
}


/**
 * Returns home page.
 */
function park_pages_getHomePage() {
  
  $out = '';
  
  global $user;
  if (!$user->uid) {
    $out .= '<div id="mws"></div><script type="text/javascript" src="http://mws.all4senses.com/mws.js"></script>';
  }
  
  $front_preface_node = park_pages_getPrefaceByKey('front');
  $front_preface_node->title_no_link = TRUE;
  $front_preface_node_view = node_view($front_preface_node, 'full');

  $out .= render($front_preface_node_view);
  
  /*
  // Get block for Top pick business providers.
  $block_data = array('module' => 'views', 'delta' => 'providers-block', 'shadow' => FALSE);
  $out .= gcb_blocks_getBlockThemed($block_data);
  */
  
  $out .= render($front_preface_node_view['field_preface_bottom']);
 
  return $out;
}



/**
 * Returns preface node by key.
 */
function park_pages_getPrefaceByKey($key) {
    
    $preface_node = NULL;
    
    $query = db_select('node', 'n');
    $query->join('field_data_field_preface_key', 'pk', "pk.entity_id = n.nid"); 
    $query->fields('n', array('nid'))  
          //->fields('pn', array('field_preface_key_value')) 
          ->condition('n.type', 'preface')
          ->condition('pk.field_preface_key_value', $key); 
    $preface_nid = $query->execute()->fetchField(); 
    if ($preface_nid) {
      $preface_node = node_load($preface_nid);
    }
    return $preface_node;
}


/**
 * Returns section's blocks.
 */
function park_pages_getSectionBlocks($node) {
  
  if (!isset($node->field_tags['und']) || empty($node->field_tags['und'])) {
    return;
  }
  
  $node->sectionBlocks = array();
  $tids = NULL;
  
  //dpm($node->field_tags['und']);
  foreach($node->field_tags['und'] as $term) {
    $tids[$term['tid']] = $term['tid'];
    $allTags[$term['taxonomy_term']->name] = $term['taxonomy_term'];
  }

  
  
  
  
  // Add tags filter block.

  $url_tags = explode(',', @$_GET['tags-exclude']);
  foreach ($allTags as $tag_name => $tag_data) {
    if (!in_array($tag_name, $url_tags)) {
      $selectedTags[$tag_data->tid] = $tag_name;
    }
    else {
      unset($tids[$tag_data->tid]);
    }
  }
  
  $selectTags = park_pages_themeTagsSelect($allTags, $selectedTags);
  
  $node->sectionBlocks['selectTags'] = '<div class="filter-block">' . $selectTags . '<div id="sectionIsFiltered">' . t('The section is filtered, some content is excluded by the tags filter. You may include it back by selecting excluded tags.') . '</div></div>';
          
  drupal_add_js('sites/all/libraries/jquery.plugins/chosen.jquery/chosen.jquery.js');
  drupal_add_css('sites/all/libraries/jquery.plugins/chosen.jquery/chosen.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)

  $path_to_module = drupal_get_path('module', 'park_pages');
  drupal_add_js($path_to_module . '/js/park_sectionFilter.js');
  
 
  
  
  
  
  
  
  // Add content blocks.
  
  $view_name = 'section_blocks';
  $display_name = 'section_titles_block';
  $viewsFilterOptions_tid = array('id' => 'tid', 'value' => $tids, 'type' => 'select', 'vid' =>  'tags', 'hierarchy' => 1, 'reduce_duplicates' => 1, 'group' => 0);
  $nodeTypesToShow = array('article' => 'Статьи', 'album' => 'Альбомы', 'master_class' => 'Мастер-классы', 'blog_post' => 'Посты в Блогах');
  
  foreach ($nodeTypesToShow as $type => $title) {
    $view = views_get_view($view_name);
    $view->add_item($display_name, 'filter', 'taxonomy_index', 'tid', $viewsFilterOptions_tid);
    $viewsFilterOptions_nodeType = array('id' => 'type', 'value' => array($type => $type));
    $view->add_item($display_name, 'filter', 'node', 'type', $viewsFilterOptions_nodeType);

    $results = $view->preview($display_name);
    if ($view->total_rows) {
      $node->sectionBlocks[$type] = '<h3>' . $title . '</h3>' . $results;
      //$node->sectionBlocks[$display] = $view->render($display);
    }
  } // End of foreach ($nodeTypesToShow as $type => $title) {
  
  
  // Add authors blocks.
  
  $view_name = 'section_users_blocks';
  $display_name = 'section_users_titles_block';
  $view = views_get_view($view_name);
  $viewsFilterOptions_authors = array(
    'id' => 'tid', 
    'value' => $tids,
    'relationship' => 'uid',
    'type' => 'select',
    'reduce_duplicates' => 1,
    'vocabulary' => 'tags',
    'hierarchy' => 1,
  );
  
  $view->add_item($display_name, 'filter', 'taxonomy_index', 'tid', $viewsFilterOptions_authors);

  $results = $view->preview($display_name);
  if ($view->total_rows) {
    $node->sectionBlocks['authors'] = '<h3>' . 'Авторы' . '</h3>' . $results;
    //$node->sectionBlocks[$display] = $view->render($display);
  }
  
}


/**
 * Returns themed TagsSelect blocks.
 */
function park_pages_themeTagsSelect($tags = NULL, $selected_terms = array(), $disabled_terms = array()) {
  
  if (empty($tags)) {
    return;
  }
  
  $selectTags = '<select id="select-tags" data-placeholder="' . t('Select tags') . '" style="width:350px;" multiple class="chzn-select" tabindex="8">
          <option value=""></option>';
  foreach ($tags as $tag) {
    $selectTags .= '<option value="' . $tag->name . '"' . (in_array($tag->name, $selected_terms) ? ' selected': '') . (in_array($tag->name, $disabled_terms) ? ' disabled': '') . '>' . $tag->name . '</option>';
  }
  $selectTags .= '</select>
        <div id="doFilter">Filter</div>';
  return $selectTags;
}


/**
 * Returns themed AuthorSelect blocks.
 */
function park_pages_themeAuthorsSelect($selected_username = NULL, $all_authors = array(), $eligible_authors = array()) {
  
  if (empty($all_authors)) {
    return NULL;
  }
  
  //dpm($all_authors);
  
  $selectTags = '<select id="select-authors" data-placeholder="' . t('Select author') . '" style="width:350px;" class="chzn-select" tabindex="8">
          <option value=""></option>';
  
  foreach ($all_authors as $username => $realname) {
    $selectTags .= '<option value="' . $username . '"' . ($username == $selected_username ? ' selected': '') . (!in_array($realname, $eligible_authors) ? ' disabled': '') . '>' . $realname . '</option>';
  }
  $selectTags .= '</select>
        <div id="goToAuthorPage">' . t("Visit this author's profile") . '</div>';
  
  return $selectTags;
}


/**
 * Returns content feed for a specific content type.
 */
function park_pages_getContentFeedWithControls($type, $uid = NULL, $default_list_view_style = 'teaser') {
  
  $terms = NULL;
  $allTags = NULL;
  $url_tags = NULL;
  $selectTags = NULL;
  
  $query = db_select('taxonomy_term_data', 'td')
        ->fields('td', array('name', 'tid'));
  $query->leftJoin('taxonomy_index', 'ti', 'ti.tid = td.tid');
  $query->leftJoin('node', 'n', 'n.nid = ti.nid');
  $query->where('n.nid = ti.nid AND n.type = :type', array(':type' => $type))
        ->addExpression('COUNT(n.nid)', 'count');
  $query->groupBy('td.name');
  $query->condition('td.vid', 1);
  $results = $query->execute();
  foreach($results as $result) {
    $allTags[$result->tid] = /*(array)*/ $result;
  }
  
  
  // Build a tags block.
  if ($allTags) {
    $url_tags = explode(',', @$_GET['tags']);
    $selectTags = '<div class="filter-block">' . park_pages_themeTagsSelect($allTags, $url_tags) . '</div>';

    drupal_add_js('sites/all/libraries/jquery.plugins/chosen.jquery/chosen.jquery.js');
    drupal_add_css('sites/all/libraries/jquery.plugins/chosen.jquery/chosen.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)

    $path_to_module = drupal_get_path('module', 'park_pages');
    drupal_add_js($path_to_module . '/js/park_contentFilter.js');
  }
  
  
  $currentUrl = ltrim($_SERVER['REDIRECT_URL'], '/');
  
  // Teasers by default
  if ($default_list_view_style == 'teaser') {
    $currentViewStyle = (isset($_GET['view']) && $_GET['view'] == 'titles') ? 'titles' : 'teasers';
  }
  else {
    $currentViewStyle = (isset($_GET['view']) && $_GET['view'] == 'teasers') ? 'teasers': 'titles';
  }
  

  $view_name = 'content_feeds';
  $display_name = ($currentViewStyle == 'teasers') ? 'content_feed_teasers_block' : 'content_feed_titles_block';
  $view = views_get_view($view_name);
  $viewsFilterOptions_nodeType = array('id' => 'type', 'value' => array($type => $type));
  $view->add_item($display_name, 'filter', 'node', 'type', $viewsFilterOptions_nodeType);
  
  
  if ($url_tags) {
    //$url_tags = explode(',', $_GET['tags']); //array('бисер', 'дизайн');
    $query = db_select('taxonomy_term_data', 'td');
    $query->fields('td', array('tid'))
          ->condition('td.name', $url_tags, 'IN');
    $tids = $query->distinct()
    ->execute()->fetchCol();
    
    if ($tids) {
      foreach ($tids as $tid) {
        $options[$tid] = $tid;
      }
      $viewsFilterOptions_tids = array('id' => 'tid', 'reduce_duplicates' => 1, 'type' => 'select', 'vocabulary' => 'tags', 'value' => $options);
      $view->add_item($display_name, 'filter', 'taxonomy_index', 'tid', $viewsFilterOptions_tids);
    }
  }
  
  
  
  $users_select = NULL;
  
  if ($uid) {
    
    // Call from a user page.
    
    $viewsFilterOptions_user = array('id' => 'uid', 'value' => array(0 => $uid));
    $view->add_item($display_name, 'filter', 'node', 'uid', $viewsFilterOptions_user);
  }
  else {
    
    // Call from a content page.
    
    $url_uid = @$_GET['author'];
    if ($url_uid) {
      $viewsFilterOptions_user = array('id' => 'uid', 'value' => array(0 => $url_uid));
      $view->add_item($display_name, 'filter', 'node', 'uid', $viewsFilterOptions_user);
    }
    // Get all users that have content of a specific type

    $query = db_select('node', 'n');
    $query->leftJoin('users', 'u', 'u.uid = n.uid');
    $query->leftJoin('realname', 'rn', 'rn.uid = n.uid');

    $query->fields('u', array('uid', 'name'))
          ->fields('rn', array('realname'))
          ->condition('n.type', $type)
          ->condition('n.status', 1);

    $users = $query->distinct()
    ->execute();

    $all_authors = NULL;
    foreach ($users as $user) {
      $all_authors[$user->name] = $user->realname;
    }


    // Refine conditions and get only users that have specific tag in their content (of a specific type)
    if (@$tids) {
      $or = db_or();
  //    foreach ($tids as $count => $tid) {
  //      $query->leftJoin('taxonomy_index', "ti_$count", "ti_$count.nid = n.nid AND ti_$count.tid = $tid");
  //    }
      foreach ($tids as $count => $tid) {
        $query->leftJoin('taxonomy_index', "ti_$count", "ti_$count.nid = n.nid AND ti_$count.tid = $tid");
        $or->condition("ti_$count.tid", $tid);
      }
      $query->condition($or);
    }

    $users = $query->distinct()
    ->execute();

    $eligible_authors = NULL;

    foreach ($users as $user) {
      $eligible_authors[$user->name] = $user->realname;
    }

    $users_select = '<div class="filter-block">' . park_pages_themeAuthorsSelect($url_uid, $all_authors, $eligible_authors) . '</div>';
  }
      
      
      
  $results = $view->preview($display_name);
  if ($view->total_rows) {
    
    $get = $_GET;
    unset($get['q']);
    if ($currentViewStyle == 'teasers') {
      $get['view'] = 'titles';
      $newViewStyleTitle = t('View Titles');
      $currentViewStyleTitle = t('View Teasers');
    }
    else {
      $get['view'] = 'teasers';
      $newViewStyleTitle = t('View Teasers');
      $currentViewStyleTitle = t('View Titles');
    }
    
  }
  else {
    $results = '<div class="results">' . t('No content found.') . '</div>';
  }
  
  
  $viewStyle = !@$currentViewStyleTitle ? '' : '<div class="view-style"><span>' . $currentViewStyleTitle . '</span>  | ' . l($newViewStyleTitle, $currentUrl, array('query' => $get)) . '</div>';
  $controlBlock = '<div class="feed-control">' . $viewStyle . $users_select . $selectTags . '</div>';
  
  return $controlBlock . $results;
}


/**
 * Implements hook node_view.
 */
function park_pages_node_view($node) {
  switch ($node->type) {
    case 'section':
      park_pages_getSectionBlocks($node);
      break;
    
    case 'preface':
      $key = @$node->field_preface_key['und'][0]['value'];
      switch($key) {
        case 'master_class':
        case 'article':
        case 'album':
          $node->contentFeed = park_pages_getContentFeedWithControls($key);
          break;
      }
      break; // End of 'preface'
  } // End of switch ($node->type) {
  
}


/**
 * Returns miniteasers.
 */
function park_pages_buildMiniTeasersSet($nids){
    
    $build = null;
    if(is_array($nids))
        foreach($nids as $nid)
        {
            if($node = db_query("SELECT u.name, n.nid, n.title, n.created AS date, i.field_main_image_value AS main_image, a.alias AS node_url
                                FROM {node} n 
                                LEFT JOIN {users} u ON u.uid = n.uid
                                LEFT JOIN {field_data_field_main_image} i ON i.entity_type = 'node' AND i.entity_id = n.nid 
                                LEFT JOIN {url_alias} a ON a.source = 'node/" . $nid . "' 
                                WHERE n.nid = :nid", 
                        array(':nid' => $nid)
                    )->fetchObject())
            {
            
                $build['nodes'][] = array(
                            '#theme' => 'park_pages_ImageMiniTeaser',
                            '#node' => $node,
                            );
            }
            /*
            $build['nodes'] = array(
                        0 => array(
                          '#theme' => 'park_pages_ImageMiniTeaser',
                          //'#weight' => -10,
                          '#node' => array(
                                    0 => '11111',
                                    1 => '22222',
                                    '#markup' => '<div>yyy</div>',
                                ),
                        ),
                        1 => array(
                          '#theme' => 'park_pages_ImageMiniTeaser',
                          //'#weight' => -10,
                          '#node' => array(
                                    0 => '3333',
                                    1 => '4444',
                                ),
                          '#weight' => -5,
                        ),
                        '#weight' => -5,
            );
            */
        }
    
    return $build;    
}


/**
 * Returns user's content.
 */
function park_pages_getUserContent($account, $type, $singular_title, $plural_title, $build_condition = array(), $build_function = null){
    
  global $user;  
  
  drupal_set_title($title = t("@name's " . $plural_title, array('@name' => format_username($account))), PASS_THROUGH);

  $build = array();

  $query = db_select('node', 'n')->extend('PagerDefault');
  $nids = $query
    ->fields('n', array('nid', 'sticky', 'created'))
    ->condition('type', $type)
    ->condition('uid', $account->uid)
    ->condition('status', 1)
    ->orderBy('sticky', 'DESC')
    ->orderBy('created', 'DESC')
    ->limit(variable_get('default_nodes_main', 10))
    ->addTag('node_access')
    ->execute()
    ->fetchCol();

  if (!empty($nids)) {
    if($build_function 
            AND isset($_GET[$build_condition[0]]) 
            AND $_GET[$build_condition[0]] == $build_condition[1]
            AND is_array($nodes = $build_function($nids))
      )
    {
        $build += $nodes;;
        //$build_function($nids);
    }
    else
    {
        $nodes = node_load_multiple($nids);
        $build += node_view_multiple($nodes);
    }
    $build['pager'] = array(
      '#theme' => 'pager',
      '#weight' => 5,
    );
  }
  else {
    if ($account->uid == $user->uid) {
      drupal_set_message(t('You have not yet created any ' . $singular_title . ' entries.'));
    }
    else {
      drupal_set_message(t('!author has not yet created any ' . $singular_title . ' entries.', array('!author' => theme('username', array('account' => $account)))));
    }
  }
  /////drupal_add_feed('blog/' . $account->uid . '/feed', t('RSS - !title', array('!title' => $title)));


//$build += $temp;
//$build['my'][0] = '<div>yyy</div>';
  return $build;
}


/**
 * Implements hook theme.
 */
function park_pages_theme($existing, $type, $theme, $path) {
  return array(
    'park_pages_ImageMiniTeaser' => array(
      'variables' => array('node' => array()),
      //'path' => path_to_theme(),
      'template' => 'park_pages_ImageMiniTeaser',
    ),  
            
  );
}


/**
 * Implements hook node_presave.
 */
function park_pages_node_presave($node) {
  
    // Build teaser, gallery, find images (main, sharing, etc).
  
    $content_with_teaser = array('article', 'master_class', 'album', 'blog_post');
    $content_with_teaser_and_slideshow = array('master_class', 'album');
    
    if (in_array($node->type, $content_with_teaser)) {
      
      // If this is a new node, yet without nid, let's find out supposed its id
      if(!$nid = $node->nid) {
        $nid = db_next_id(db_query('SELECT MAX(nid) FROM {node}')->fetchField());
      }

      $extra_data = park_pages_getExtraDataFromBody($node->body['und'][0]['value'], $nid, $node->type);
         
      if(in_array($node->type, $content_with_teaser_and_slideshow) && $body_images = park_image_findImages($node->body['und'][0]['value'], $nid)) {
        //$node->field_main_image['und'][0]['value'] = serialize($body_images[0]);
        //$node->field_body_to_gallery['und'][0]['value'] = park_image_prepareBodyToSlideshow($nid, $gallery);
        $extra_data['slideshow_themed'] = park_image_prepareBodyToSlideshow($nid, $body_images);
      }
      
      $node->field_extra_data['und'][0]['value'] = serialize($extra_data);
      
      
    } // End of if (in_array($node->type, $content_with_teaser)) {
}


/**
 * Build a trimmed teaser, a main image, a sharing image, etc from a source body.
 */
function park_pages_getExtraDataFromBody($body, $nid, $content_type = NULL, $characters_num = NULL, $only_teaser = FALSE) {
 
  $main_image_html = NULL;
  $main_image = NULL;
  $matches = NULL;

  // Get the main image for a teaser and for sharing
  // and then clear img tags from the body.
  if (preg_match('/<img[^>]+>/i', $body, $matches)) {
    
    preg_match_all('/(alt|title|src)="([^"]*)"/i', $matches[0], $matches);
    foreach ($matches[1] as $index => $key) {
      $main_image[$key] = $matches[2][$index];
    }
    $main_image['src'] = str_replace('%20', ' ', $main_image['src']);
    $stream_path = park_misc_getStreamUriFromRelativePath($main_image['src']);
    $main_image['uri'] = $stream_path;
    
    $image_size = getimagesize(ltrim($main_image['src'], '/'));

    // Scale and cut.
    /*
    if ($image_size[0] / $image_size[1] > 1.5) {
      $main_image_html = theme('image_style', array( 'path' => $stream_path, 'style_name' => 'article_thumbnail_h'));
    }
    else {
      $main_image_html = theme('image_style', array( 'path' => $stream_path, 'style_name' => 'article_thumbnail_v'));
    }
    */

    // Scale only.
    if ($image_size[0] / $image_size[1] > 1) {
      $style_name = 'teaser_thumb_h';
      $main_image_html = theme('image_style', array( 'path' => $stream_path, 'style_name' => $style_name));
    }
    else {
      $style_name = 'teaser_thumb_v';
      $main_image_html = theme('image_style', array( 'path' => $stream_path, 'style_name' => $style_name));
    }
    
    // Image for sharing.
    if ($image_size[0] / $image_size[1] > 1) {
      // Too wide. will not be cutted.
      $main_image['share_themed'] = image_style_url('share_wide', $stream_path);
    }
    elseif ($image_size[1] / $image_size[0] < 1) {
      // Too tall. will not be cutted.
      $main_image['share_themed'] = image_style_url('share_tall', $stream_path);
    }
    else {
      //Normal image, will not be cutted.
      $main_image['share_themed'] = image_style_url('share', $stream_path);
    }
    
    $main_image_html = '<div class="thumb">' . $main_image_html . '</div>';
    
    // Clear img tags out of a body.
    $body = preg_replace('/<img[^>]+>/i', '', $body);
  }

  if (!$characters_num) {
    if ($main_image_html) {
      $characters_num = 130;
    }
    else {
      $characters_num = 250;
    }
  }
  
  // $teaser = text_summary($body_full_markup, 'full_html', $characters_num);
  $teaser = strip_tags($body);
  $teaser = trim(drupal_substr($teaser, 0, $characters_num));
  
  // Replace the last word with ...
  // preg_match('/^.*\s(.*)$/i', trim(strip_tags($teaser)), $matches);
  // $last_pos = strrpos($teaser, $matches[1]);
  $last_pos = strrpos($teaser, ' ');
  $teaser = substr_replace($teaser, '... ' . l(t('Read More'), 'node/' . $nid, array('attributes' => array('class' => array('more')))), $last_pos);

  if ($only_teaser) {
    return $main_image_html . $teaser;
  }
  else {
    return array('teaser' => $main_image_html . $teaser, 'main_image' => $main_image);
  }
  
}
