<?php

/**
 * Implements hook_menu().
 */
function park_social_menu() {
    
  $items = array();
  
  /*
  // Look at the inc file.      
  $items['user/%user/social'] = array( 
      'title' => t('Social connect'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('park_social_socialPageForm', 1),
      ////'page callback' => 'park_social_socialPageShow', 
      //'page arguments' => array(1, 'album', 'album', 'albums', array('t','mini'), 'park_pages_buildMiniTeasersSet'),
      ////'page arguments' => array(1),
      
      'access arguments' => array('access content'),
      'type' => MENU_LOCAL_TASK,
    );  
*/
  $items['authsub'] = array (
    'page callback' => 'park_social_authsub_redirect',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}


/**
 * Redirect different app types auths to appropriate calling paths.
 */
function park_social_authsub_redirect()
{
    if(!isset($_GET['redirect']))
        drupal_goto();
    
    $redirect_query = "http://".$_SERVER['SERVER_NAME'] . '/' . ltrim($_GET['redirect'], '/') . '?';
    unset($_GET['q'], $_GET['redirect']);
    $count = 0;
    foreach($_GET as $key=>$param)
        if($count++ > 0)
            $redirect_query .= '&' . $key . '=' . $param;
        else
            $redirect_query .= $key . '=' . $param;
        
    drupal_goto($redirect_query);
}


/**
 * Implements hook_theme().
 */
function park_social_theme($existing, $type, $theme, $path) {
  return array(
    'park_social_socialPageForm' => array(
      'path' => path_to_theme() . '/templates',
      'template' => 'park_socialPage',
      'render element' => 'form',
    ),  
            
  );
}


/**
 * Implements hook_block_info().
 */
function park_social_block_info() {
  
  $blocks['hc_recent_comments'] = array(
    'info' => t('HC Recent comments'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['hc_popular_articles'] = array(
    'info' => t('HC Popular articles'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function park_social_block_view($delta = '') {
  
  $block = array();
  switch ($delta) {      
    
    case 'hc_recent_comments':
      $block['subject'] = t('HC Recent comments');
      $block['content'] = park_social_hcBlocks('recent_comments');
      break;
    case 'hc_popular_articles':
      $block['subject'] = t('HC Popular articles');
      $block['content'] = park_social_hcBlocks('popular_articles');
      break;

  }

  return $block;
}


/**
 * Builds HyperComments blocks.
 */
function park_social_hcBlocks($block_type) {
  
  switch ($block_type) {
    
    case 'recent_comments':
      $path_to_module = drupal_get_path('module', 'park_social');
      drupal_add_js($path_to_module . '/js/park_hcRecentComments.js');
      return '<div id="hypercomments_mix"></div>';
    
    
    case 'popular_articles':
      $path_to_module = drupal_get_path('module', 'park_social');
      drupal_add_js($path_to_module . '/js/park_hcPopularArticles.js');
      return '<div id="hypercomments_mix"></div>';
          
  }
}