<?php

/**
 * Implementation of hook_menu().
 */
/*
function park_image_menu() {
    
  $items = array();
  // ...
  return $items;
  
}
*/



/**
 * Launch a slider.
 */
function park_image_getSlideshow($type = NULL, $id = NULL) {

  
  
  //drupal_add_js(array('park_image' => array('group_' . $node->nid => 1)), 'setting');
  
  switch ($type) {
    
    case 'Sequense':
      
      park_image_addSequenceSlideshowJs();
      
      $out = '
    
          <img class="prev" src="sites/all/libraries/jquery.plugins/sequence/themes/modern-slide-in/images/bt-prev.png" alt="Previous Frame" />
          <img class="next" src="sites/all/libraries/jquery.plugins/sequence/themes/modern-slide-in/images/bt-next.png" alt="Next Frame" />
          <div id="sequence" style="height: 600px;">
              <ul>
                <li id="intro">
                  <h2 class="title animate-in">Built using Sequence.js</h2>
                  <h3 class="subtitle animate-in">The Responsive Slider with Advanced CSS3 Transitions</h3>
                  <img class="model animate-in" src="sites/all/libraries/jquery.plugins/sequence/themes/modern-slide-in/images/model1.png" alt="Model 1" />
                </li>
                <li id="creative">
                  <h2 class="title">Creative Control</h2>
                  <h3 class="subtitle">Create unique sliders using CSS3 transitions</h3>
                  <img class="model" src="sites/all/libraries/jquery.plugins/sequence/themes/modern-slide-in/images/model2.png" alt="Model 2" />
                </li>
                <li id="support" class="frame3">
                  <h2 class="title">Cutting Edge</h2>
                  <h3 class="subtitle">Supports modern browsers, old browsers (IE7+), touch devices and responsive designs</h3>
                  <img class="model" src="sites/all/libraries/jquery.plugins/sequence/themes/modern-slide-in/images/model3.png" alt="Model 3" />
                </li>
              </ul>
            </div>
            <ul id="nav">
              <li><img src="sites/all/libraries/jquery.plugins/sequence/themes/modern-slide-in/images/tn-model1.png" alt="Model 1" /></li>
              <li><img src="sites/all/libraries/jquery.plugins/sequence/themes/modern-slide-in/images/tn-model2.png" alt="Model 2" /></li>
              <li><img src="sites/all/libraries/jquery.plugins/sequence/themes/modern-slide-in/images/tn-model3.png" alt="Model 3" /></li>
            </ul>
        ';
      
      break;
    
    
    
    case 'AdvancedSlider':
      
      park_image_addAdvancedSliderJs();
      
      $out = '
    
          <div class="advanced-slider glossy-square-blue" id="responsive-slider">
            <ul class="slides">
              <li class="slide">
                <a rel="slider-lightbox[]" href="http://www.youtube.com/watch?v=JVuUwvUUPro?width=700&height=400" title="Some lightbox description">
                  <img class="image" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/slides/image1.jpg" alt=""/>
                </a>
                
                  <img class="thumbnail" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/thumbnails/image1.jpg" alt="Slide 1"/>
                <div class="caption">This is just a simple caption.</div>
              </li>

              <li class="slide rounded-caption">
              <div class="html">
                <div class="images-box">
                    <img src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/thumbnails/image2.jpg" alt=""/>
                    <img src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/thumbnails/image2.jpg" alt=""/>
                    <img src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/thumbnails/image2.jpg" alt=""/>
                    <img src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/thumbnails/image2.jpg" alt=""/>
                </div>
					
                <div class="content-box">
                    <p class="title">Inline HTML content</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    <a class="button" href="#">Read More</a>
                </div>
            </div>
            
                <img class="image" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/slides/image2.jpg" alt=""/>
                  <img class="thumbnail" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/thumbnails/image2.jpg" alt="Slide 2"/>
                <div class="caption"><b><i>Custom size and position</i></b> <br/><br/> You can set the caption\'s position to left, right, top or bottom, but you can also give it a custom position and size, as you can see in this example. Also, you can choose from 2 caption effects: slide and fade.</div>
              </li>

              <li class="slide">
                <img class="image" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/slides/image3.jpg" alt=""/>
                  <img class="thumbnail" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/thumbnails/image3.jpg" alt="Slide 3"/>
              </li>

              <li class="slide">
                <img class="image" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/slides/image4.jpg" alt=""/>
                  <img class="thumbnail" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/thumbnails/image4.jpg" alt="Slide 4"/>
                <div class="caption">You can also add <b>HTML</b> elements like <a href="http://codecanyon.net">links</a> or <input type="button" value="Buttons"/></div>
              </li>

              <li class="slide">
                <img class="image" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/slides/image5.jpg" alt=""/>
                  <img class="thumbnail" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/thumbnails/image5.jpg" alt="Slide 5"/>
              </li>

              <li class="slide">
                <img class="image" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/slides/image6.jpg" alt=""/>
                  <img class="thumbnail" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/thumbnails/image6.jpg" alt="Slide 6"/>
                <div class="caption"><u>Title</u><br/><br/>This is a list of items:<ul><li>first item</li><li>second item</li><li>third item</li></ul></div>
              </li>

              <li class="slide">
                <img class="image" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/slides/image7.jpg" alt=""/>
                  <img class="thumbnail" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/thumbnails/image7.jpg" alt="Slide 7"/>
              </li>

              <li class="slide">
                <img class="image" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/slides/image8.jpg" alt=""/>
                  <img class="thumbnail" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/thumbnails/image8.jpg" alt="Slide 8"/>
                <div class="caption"><u>Title</u><br/><br/><br/>List of items:<ul><li>first item</li><li>second item</li><li>third item</li></ul></div>
              </li>

              <li class="slide">
                <img class="image" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/slides/image9.jpg" alt=""/>
                  <img class="thumbnail" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/thumbnails/image9.jpg" alt="Slide 9"/>
              </li>

              <li class="slide">
                <img class="image" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/slides/image10.jpg" alt=""/>
                  <img class="thumbnail" src="sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/images/thumbnails/image10.jpg" alt="Slide 10"/>
              </li>
            </ul>
          </div>

        ';
      
      break;
  }
  
  
  return $out;
}


/**
 * Adds js to a page for a AdvancedSlider slideshow.
 */
function park_image_addAdvancedSliderJs() {
  
  
  
  //drupal_add_js('sites/all/libraries/jquery.plugins/advanced_slider/excanvas.compiled.js');
  drupal_add_js('sites/all/libraries/jquery.plugins/advanced_slider/jquery.transition.min.js');
  drupal_add_js('sites/all/libraries/jquery.plugins/advanced_slider/jquery.touchSwipe.min.js');
  drupal_add_js('sites/all/libraries/jquery.plugins/advanced_slider/jquery.advancedSlider.min.js');
  
  drupal_add_js('sites/all/libraries/jquery.plugins/advanced_slider/jquery.prettyPhoto.custom.min.js');
  
  drupal_add_css('sites/all/libraries/jquery.plugins/advanced_slider/css/base/advanced-slider-base.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)
  drupal_add_css('sites/all/libraries/jquery.plugins/advanced_slider/examples/responsive-proportional/css/glossy-square/blue/glossy-square-blue.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)  
  ////drupal_add_css('sites/all/libraries/jquery.plugins/advanced_slider/examples/responsive-proportional/css/responsive-proportional-slider.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)  
  //
//drupal_add_css('sites/all/libraries/jquery.plugins/advanced_slider/examples/basic/css/pixel/pixel.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)
  
  //drupal_add_css('http://fonts.googleapis.com/css?family=Ruluko|Sirin+Stencil', array('preprocess' => FALSE, 'external' => TRUE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)
  
  drupal_add_css('sites/all/libraries/jquery.plugins/advanced_slider/examples/presentation-assets/presentation.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)  
  
  
  
  
  
  
  
  $path_to_module = drupal_get_path('module', 'park_image');
  drupal_add_js($path_to_module . '/js/park_add_advancedSlider.js');
  //drupal_add_css($path_to_module . '/css/park_add_advancedSlider.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)
}


/**
 * Adds js to a page for a Sequence slideshow.
 */
function park_image_addSequenceSlideshowJs() {
  
  drupal_add_js('sites/all/libraries/jquery.plugins/sequence/sequence.jquery-min.js');
  //drupal_add_css('sites/all/libraries/jquery.plugins/sequence/css/sequencejs-theme.dev.how-it-works.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)
  
  drupal_add_css('sites/all/libraries/jquery.plugins/sequence/themes/modern-slide-in/css/sequencejs-theme.modern-slide-in.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)
  
//drupal_add_css('sites/all/libraries/jquery.plugins/sequence/demo-assets/css/demo-styles.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)

  drupal_add_css('http://fonts.googleapis.com/css?family=Ruluko|Sirin+Stencil', array('preprocess' => FALSE, 'external' => TRUE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)
  
  
  $path_to_module = drupal_get_path('module', 'park_image');
  drupal_add_js($path_to_module . '/js/park_add_sequenceSlideshow.js');
  //drupal_add_css($path_to_module . '/css/park_add_sequenceSlideshow.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)
}


/**
 * Implements hook form_alter.
 */
function park_image_form_alter(&$form, &$form_state, $form_id) {
  
  //dpm($form_id); dpm($form);

  switch($form_id) {
    case 'album_node_form':
    case 'master_class_node_form':
        // Hide placeholder fields on the edit form.
        $form['field_body_to_gallery']['#type'] = 'hidden';
        $form['field_main_image']['#type'] = 'hidden';
        break;
  }

}


/**
 * Finds images in a body html.
 */
function park_image_findImages($body, $nid, $amount = null){ 
    // $amount - how many images to include in the result array
    
    /* // in template
     preg_match_all("/<img[^']*?src=\"([^']*?)\"[^']*?>/", $content['body']['#items'][0]['value'], $matches, PREG_SET_ORDER);
    */
    preg_match_all("/<img[^']*?src=\"([^']*?)\"[^']*?>/", $body, $matches, PREG_SET_ORDER);
    
    // find the rest img data
    
    $gallery = null;
    
    if(is_array($matches))
        foreach($matches as $key=>$match)
        {
            $cur_img = array();

            preg_match_all('/(alt|title|class)="([^"]*)"/i',$match[0], $matches2, PREG_SET_ORDER);
            foreach($matches2 as $match2)
                $cur_img[$match2[1]] = $match2[2];
            $cur_img['src'] = $match[1];
            
            // just in case, save themed img tag
            // with default preset - redefine it if needed !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            $cur_img['style_name'] = 'album_thumb';
            $default_file_path = variable_get('file_public_path', 'f');
            $cur_img['path'] = str_replace('/' . $default_file_path . '/', 'public://', $cur_img['src']);
            $cur_img['thumb'] = theme('image_style', $cur_img);
            $cur_img['class'] = 'group_' . $nid;
            $gallery[] = $cur_img;

            if($amount AND $key + 1 == $amount)
                break;
        }  
    
    return $gallery;
}


/**
 * Returns themed slideshow html to keep in in the placeholder body_to_gallery.
 */
function park_image_prepareBodyToSlideshow($nid, $gallery) {
    
    $links_collection_for_colobox = '';
    $body_to_slideshow =  ''
        //. '<fieldset class="collapsible collapsed form-wrapper"><legend>test</legend>'
        . '<div id="gallery_wrapper_' . $nid . '" class="slideshows">'
                //.'<div id="gallery_' . $key . '" class="ad-gallery">'
                .'<div id="adg'. $nid . '" class="ad-gallery">'
                    .'<div class="ad-image-wrapper" style="width:600px;height:400px;"></div>'
                    .'<div class="ad-controls"></div>'
            
                    // my button for full screen in ColorBox
                    // set up in park_image_gallery_ad.js
                    . '<div class="full_screen_btn"><a class="full group_' . $nid . '" href="">Full screen</a></div>'
            
                    .'<div class="ad-nav">'
                        .'<div class="ad-thumbs">'
                            .'<ul class="ad-thumb-list">';
    
                                $default_file_path = variable_get('file_public_path', conf_path() . '/files');
                                foreach($gallery as $key2 => $image)
                                {
                                    $attributes = array();
                                    $image_data = array();
                                    
                                    if(isset($image['longdesc']))
                                            $attributes['longdesc'] = $image['longdesc'];
                                    //if(isset($image['class']))
                                    //        $attributes['class'] = $image['class'];
                                    
                                    //$image_data['path'] = str_replace('/sites/default/files/', 'public://', $image['thumb']);
                                    $image_data['path'] = str_replace('/' .$default_file_path . '/', 'public://', $image['src']);
                                    
                                    $image_data['style_name'] = 'album_thumb';
                                    
                                    if(isset($image['alt']))
                                            $image_data['alt'] = $image['alt'];
                                    if(isset($image['title']))
                                            $image_data['title'] = $image['title'];
                                    
                                    $image_data['attributes'] = $attributes;
                                    //$links_collection_for_colobox .= '<a style="display:none;" class="' . $image['class'] . '" href="' . $image['src'] . '">Full screen</a>';
                                    $body_to_slideshow .= 
                                          '<li>'
                                            //.'<a href="' . $image['src'] . '">'
                                            .'<a class="' . $image['class'] . '" href="http://' . $_SERVER['SERVER_NAME'] . $image['src'] . '">'
                                                //.'<img src="' . $image['thumb'] . '"' . (isset($image['title'])?' title="' . $image['title'] . '"':'') . (isset($image['alt'])?' alt="' . $image['alt'] . '"':'') . (isset($image['longdesc'])?' longdesc="' . $image['longdesc'] . '"':'') . ' class="image' . $key2 . '">'
                                                . theme('image_style', $image_data)
                                           .'</a>'
                                        .'</li>';
                                }
                        $body_to_slideshow .= '</ul>'
                        .'</div>'
                    .'</div>'
                .'</div>'
 
                .'<div id="descriptions"></div>'
                                
                .'<p>'
                    .'Examples of how you can alter the behaviour on the fly;'
                    .'Effect: <select class="switch-effect">'
                                .'<option value="slide-hori">Slide horizontal</option>'
                                .'<option value="slide-vert">Slide vertical</option>'
                                .'<option value="resize">Shrink/grow</option>'
                                .'<option value="fade">Fade</option>'
                                //.'<option value="">None</option>'
                            .'</select><br>'

                    .'<a href="#" class="toggle-slideshow">Toggle slideshow</a> |'
                    .'<a href="#" class="toggle-description">Toggle having description outside of image</a>'
                .'</p>'
                                
        .'</div>' // end of echo '<div id="gallery_wrapper_' . $key . '">'
        //.'</fieldset>'
        ; 
                        
   //$body_to_slideshow .= $links_collection_for_colobox;
   return $body_to_slideshow;
}


/**
 * Override or insert variables into the page template.
 */
/*
function park_image_preprocess_page(&$vars) {

  return;
  if(
       (isset($vars['node']) && in_array($vars['node']->type, array('album', 'master_class', 'preface')))
          OR
       (arg(0) == 'user' && in_array(arg(2), array('albums', 'master-classes')))
          
    ) {
    park_image_addSlideShowJs();
  }
}
*/


/**
 * Implements hook node_view.
 */
function park_image_node_view($node, $view_mode) {
  
  $content_with_zoomable_pictures = array('article', 'blog_post', 'album', 'master_class', 'section');
  
  if ($view_mode == 'full') {
        
    
    $content_with_slideshow = array('album', 'master_class');
    $content_with_default_slideshow = array('album');

    // Could be 'full' or 'slideshow'.
    $show_type = 'full'; 
    
    if (in_array($node->type, $content_with_slideshow)) {
      
      $extra_data = unserialize(@$node->field_extra_data['und'][0]['value']);
      $slideshow_themed = @$extra_data['slideshow_themed'];
      //$slideshow_themed = @$node->field_body_to_gallery['und'][0]['value'];
      
      $show_type_url = @$_GET['t'];
      
      if (
            (
              //   isset($node->field_body_to_gallery['und'][0]['value']) 
              //&& $node->field_body_to_gallery['und'][0]['value']
              $slideshow_themed
            )
              AND
            (
              
                (    in_array($node->type, $content_with_default_slideshow) 
                  && (!$show_type_url || $show_type_url == 'slideshow') 

                )
                  OR
                (
                      !in_array($node->type, $content_with_default_slideshow)
                  &&  ($show_type_url && $show_type_url == 'slideshow') 
                )
            )
              
          ) {
          $show_type = 'slideshow';
      }
      
      if ($show_type == 'slideshow') {
        // Get preface text. It will be a full summary, or else cutted body.
        if (!$preface_text = $node->body['und'][0]['summary']) {
          $extra_data = unserialize(@$node->field_extra_data['und'][0]['value']);
          $preface_text = @$extra_data['summary'];
        }
        $change_show_type = '<div class="mode"><a href="' . url('node/' . $node->nid ) . (in_array($node->type, $content_with_default_slideshow) ? '?t=full' : '' ) . '" title="' . t('View in full') . '">View in full</a></div>';
        $node->main_content = $preface_text. $change_show_type . $slideshow_themed; //$node->field_body_to_gallery['und'][0]['value'];
        drupal_add_js(array('park_image' => array('group_' . $node->nid => 1)), 'setting');
        park_image_addSlideShowJs();
      }
      else {
        $change_show_type = '<div class="mode"><a href="' . url('node/' . $node->nid ) . (!in_array($node->type, $content_with_default_slideshow) ? '?t=slideshow' : '' ) . '" title="' . t('View as slideshow') . '">View as slideshow</a></div>';
        $node->main_content = $change_show_type . '<div class="full-content">' . $node->body['und'][0]['value'] . '</div>';
      }
      
    } // End of if (in_array($node->type, $content_with_slideshow)) {
    else {
      $node->main_content = '<div class="full-content">' . @$node->body['und'][0]['value'] . '</div>';
    }
    
      
    // Make zoomable picture in a normal full content for specific content types.
    if (in_array($node->type, $content_with_zoomable_pictures) && $show_type == 'full') {
      park_image_addZoomableImagesJs();
    }
    
    
  } // End of if ($view_mode == 'full') {
  else {
    // Teaser. 
    if (in_array($node->type, $content_with_zoomable_pictures)) {
      $extra_data = unserialize(@$node->field_extra_data['und'][0]['value']);
      if (@$extra_data['teaser']) {
        $node->main_content = $extra_data['teaser'];
      }
    }
  } // End of If Teaser.
            
}


/**
 * Adds slideshow js and css to a page.
 */
function park_image_addSlideShowJs() {
  drupal_add_js('sites/all/libraries/jquery.plugins/adgallery/jquery.adgallery.js');
  drupal_add_css('sites/all/libraries/jquery.plugins/adgallery/css/jquery.adgallery.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)

  //1, 3, 4, 
  drupal_add_js('sites/all/libraries/jquery.plugins/Colorbox/jquery.colorbox.js');
  drupal_add_css('sites/all/libraries/jquery.plugins/Colorbox/css1/colorbox.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)

  $path_to_module = drupal_get_path('module', 'park_image');
  drupal_add_js($path_to_module . '/js/park_add_Colorbox_ToAlbums.js');
  drupal_add_js($path_to_module . '/js/park_add_GalleryAd_ToAlbums.js');
  drupal_add_css($path_to_module . '/css/park_add_GalleryAd_ToAlbums.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)
}


/**
 * Adds js to a page for making all images zoomable.
 */
function park_image_addZoomableImagesJs() {
  //1, 3, 4, 
  drupal_add_js('sites/all/libraries/jquery.plugins/Colorbox/jquery.colorbox.js');
  drupal_add_css('sites/all/libraries/jquery.plugins/Colorbox/css1/colorbox.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)

  $path_to_module = drupal_get_path('module', 'park_image');
  drupal_add_js($path_to_module . '/js/park_makeImagesZoomable.js');
}