<?php

/**
 * Implementation of hook_menu().
 */
/*
function park_image_menu() {
    
  $items = array();
  // ...
  return $items;
  
}
*/


/**
 * Implements hook form_alter.
 */
function park_image_form_alter(&$form, &$form_state, $form_id) {
  
  //dpm($form_id); dpm($form);

  switch($form_id) {
    case 'album_node_form':
    case 'master_class_node_form':
        // Hide placeholder fields on the edit form.
        $form['field_body_to_gallery']['#type'] = 'hidden';
        $form['field_main_image']['#type'] = 'hidden';
        break;
  }

}


/**
 * Finds images in a body html.
 */
function park_image_findImages($body, $nid, $amount = null){ 
    // $amount - how many images to include in the result array
    
    /* // in template
     preg_match_all("/<img[^']*?src=\"([^']*?)\"[^']*?>/", $content['body']['#items'][0]['value'], $matches, PREG_SET_ORDER);
    */
    preg_match_all("/<img[^']*?src=\"([^']*?)\"[^']*?>/", $body, $matches, PREG_SET_ORDER);
    
    // find the rest img data
    
    $gallery = null;
    
    if(is_array($matches))
        foreach($matches as $key=>$match)
        {
            $cur_img = array();

            preg_match_all('/(alt|title|class)="([^"]*)"/i',$match[0], $matches2, PREG_SET_ORDER);
            foreach($matches2 as $match2)
                $cur_img[$match2[1]] = $match2[2];
            $cur_img['src'] = $match[1];
            
            // just in case, save themed img tag
            // with default preset - redefine it if needed !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            $cur_img['style_name'] = 'album_thumb';
            $default_file_path = variable_get('file_public_path', 'f');
            $cur_img['path'] = str_replace('/' . $default_file_path . '/', 'public://', $cur_img['src']);
            $cur_img['thumb'] = theme('image_style', $cur_img);
            $cur_img['class'] = 'group_' . $nid;
            $gallery[] = $cur_img;

            if($amount AND $key + 1 == $amount)
                break;
        }  
    
    return $gallery;
}


/**
 * Returns themed slideshow html to keep in in the placeholder body_to_gallery.
 */
function park_image_prepareBodyToSlideshow($nid, $gallery) {
    
    $links_collection_for_colobox = '';
    $body_to_slideshow =  ''
        //. '<fieldset class="collapsible collapsed form-wrapper"><legend>test</legend>'
        . '<div id="gallery_wrapper_' . $nid . '" class="slideshows">'
                //.'<div id="gallery_' . $key . '" class="ad-gallery">'
                .'<div id="adg'. $nid . '" class="ad-gallery">'
                    .'<div class="ad-image-wrapper" style="width:600px;height:400px;"></div>'
                    .'<div class="ad-controls"></div>'
            
                    // my button for full screen in ColorBox
                    // set up in park_image_gallery_ad.js
                    . '<div class="full_screen_btn"><a class="full group_' . $nid . '" href="">Full screen</a></div>'
            
                    .'<div class="ad-nav">'
                        .'<div class="ad-thumbs">'
                            .'<ul class="ad-thumb-list">';
    
                                $default_file_path = variable_get('file_public_path', conf_path() . '/files');
                                foreach($gallery as $key2 => $image)
                                {
                                    $attributes = array();
                                    $image_data = array();
                                    
                                    if(isset($image['longdesc']))
                                            $attributes['longdesc'] = $image['longdesc'];
                                    //if(isset($image['class']))
                                    //        $attributes['class'] = $image['class'];
                                    
                                    //$image_data['path'] = str_replace('/sites/default/files/', 'public://', $image['thumb']);
                                    $image_data['path'] = str_replace('/' .$default_file_path . '/', 'public://', $image['src']);
                                    
                                    $image_data['style_name'] = 'album_thumb';
                                    
                                    if(isset($image['alt']))
                                            $image_data['alt'] = $image['alt'];
                                    if(isset($image['title']))
                                            $image_data['title'] = $image['title'];
                                    
                                    $image_data['attributes'] = $attributes;
                                    //$links_collection_for_colobox .= '<a style="display:none;" class="' . $image['class'] . '" href="' . $image['src'] . '">Full screen</a>';
                                    $body_to_slideshow .= 
                                          '<li>'
                                            //.'<a href="' . $image['src'] . '">'
                                            .'<a class="' . $image['class'] . '" href="http://' . $_SERVER['SERVER_NAME'] . $image['src'] . '">'
                                                //.'<img src="' . $image['thumb'] . '"' . (isset($image['title'])?' title="' . $image['title'] . '"':'') . (isset($image['alt'])?' alt="' . $image['alt'] . '"':'') . (isset($image['longdesc'])?' longdesc="' . $image['longdesc'] . '"':'') . ' class="image' . $key2 . '">'
                                                . theme('image_style', $image_data)
                                           .'</a>'
                                        .'</li>';
                                }
                        $body_to_slideshow .= '</ul>'
                        .'</div>'
                    .'</div>'
                .'</div>'
 
                .'<div id="descriptions"></div>'
                                
                .'<p>'
                    .'Examples of how you can alter the behaviour on the fly;'
                    .'Effect: <select class="switch-effect">'
                                .'<option value="slide-hori">Slide horizontal</option>'
                                .'<option value="slide-vert">Slide vertical</option>'
                                .'<option value="resize">Shrink/grow</option>'
                                .'<option value="fade">Fade</option>'
                                //.'<option value="">None</option>'
                            .'</select><br>'

                    .'<a href="#" class="toggle-slideshow">Toggle slideshow</a> |'
                    .'<a href="#" class="toggle-description">Toggle having description outside of image</a>'
                .'</p>'
                                
        .'</div>' // end of echo '<div id="gallery_wrapper_' . $key . '">'
        //.'</fieldset>'
        ; 
                        
   //$body_to_slideshow .= $links_collection_for_colobox;
   return $body_to_slideshow;
}


/**
 * Override or insert variables into the page template.
 */
/*
function park_image_preprocess_page(&$vars) {

  return;
  if(
       (isset($vars['node']) && in_array($vars['node']->type, array('album', 'master_class', 'preface')))
          OR
       (arg(0) == 'user' && in_array(arg(2), array('albums', 'master-classes')))
          
    ) {
    park_image_addSlideShowJs();
  }
}
*/


/**
 * Implements hook node_view.
 */
function park_image_node_view($node, $view_mode) {
  
  if ($view_mode == 'full') {
        
    $content_with_zoomable_pictures = array('article', 'blog_post', 'album', 'master_class');
    $content_with_slideshow = array('album', 'master_class');
    $content_with_default_slideshow = array('album');

    // Could be 'full' or 'slideshow'.
    $show_type = 'full'; 
    
    if (in_array($node->type, $content_with_slideshow)) {
      
      $extra_data = unserialized(@$node->field_extra_data['und'][0]['value']);
      $slideshow_themed = @$extra_data['slideshow_themed'];
      
      dpm($extra_data);
      
      //$slideshow_themed = @$node->field_body_to_gallery['und'][0]['value'];
      
      $show_type_url = @$_GET['t'];
      
      if (
            (
              //   isset($node->field_body_to_gallery['und'][0]['value']) 
              //&& $node->field_body_to_gallery['und'][0]['value']
              $slideshow_themed
            )
              AND
            (
              
                (    in_array($node->type, $content_with_default_slideshow) 
                  && (!$show_type_url || $show_type_url == 'slideshow') 

                )
                  OR
                (
                      !in_array($node->type, $content_with_default_slideshow)
                  &&  ($show_type_url && $show_type_url == 'slideshow') 
                )
            )
              
          ) {
          $show_type = 'slideshow';
      }
      
      if ($show_type == 'slideshow') {
        $change_show_type = '<div class="mode"><a href="' . url('node/' . $node->nid ) . (in_array($node->type, $content_with_default_slideshow) ? '?t=full' : '' ) . '" title="' . t('View in full') . '">View in full</a></div>';
        $node->main_content = $change_show_type . $slideshow_themed; //$node->field_body_to_gallery['und'][0]['value'];
        drupal_add_js(array('park_image' => array('group_' . $node->nid => 1)), 'setting');
        park_image_addSlideShowJs();
      }
      else {
        $change_show_type = '<div class="mode"><a href="' . url('node/' . $node->nid ) . (!in_array($node->type, $content_with_default_slideshow) ? '?t=slideshow' : '' ) . '" title="' . t('View as slideshow') . '">View as slideshow</a></div>';
        $node->main_content = $change_show_type . '<div class="full-content">' . $node->body['und'][0]['value'] . '</div>';
      }
      
    }
      
    // Make zoomable picture in a normal full content for specific content types.
    if (in_array($node->type, $content_with_zoomable_pictures) && $show_type == 'full') {
      park_image_addZoomableImagesJs();
    }
    
    
  } // End of if (in_array($node->type, $content_with_slideshow)) {
            
  
}


/**
 * Adds slideshow js and css to a page.
 */
function park_image_addSlideShowJs() {
  drupal_add_js('sites/all/libraries/jquery.plugins/adgallery/jquery.adgallery.js');
  drupal_add_css('sites/all/libraries/jquery.plugins/adgallery/css/jquery.adgallery.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)

  //1, 3, 4, 
  drupal_add_js('sites/all/libraries/jquery.plugins/Colorbox/jquery.colorbox.js');
  drupal_add_css('sites/all/libraries/jquery.plugins/Colorbox/css1/colorbox.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)

  $path_to_module = drupal_get_path('module', 'park_image');
  drupal_add_js($path_to_module . '/js/park_add_Colorbox_ToAlbums.js');
  drupal_add_js($path_to_module . '/js/park_add_GalleryAd_ToAlbums.js');
  drupal_add_css($path_to_module . '/css/park_add_GalleryAd_ToAlbums.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)
}


/**
 * Adds js to a page for making all images zoomable.
 */
function park_image_addZoomableImagesJs() {
  //1, 3, 4, 
  drupal_add_js('sites/all/libraries/jquery.plugins/Colorbox/jquery.colorbox.js');
  drupal_add_css('sites/all/libraries/jquery.plugins/Colorbox/css1/colorbox.css', array('preprocess' => FALSE)); // array('group' => CSS_THEME, 'preprocess' => FALSE)

  $path_to_module = drupal_get_path('module', 'park_image');
  drupal_add_js($path_to_module . '/js/park_makeImagesZoomable.js');
}