<?php

/**
 * Implementation of hook_menu().
 */
function park_user_menu() {
  
  $items = array();
  
  $items['hc-notify'] = array(
    'page callback' => 'park_user_hcNotifyGet_ajax',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
    
  
 /* 
  $items['user/%user/blog'] = array( 
      'title' => t('User blog'),
      //'title callback' => '_guestbook_info',
      //'title arguments' => array(1, 'title'),
      'page callback' => 'park_user_getUserContent', //'wdg_user_blog_page',
      'page arguments' => array(1, 'blog_post', 'blog post', 'blog posts'),
      //'access callback' => 'guestbook_menu_access_user_guestbook',
      //'access arguments' => array(1, 'access user guestbooks'),
      'access arguments' => array('access content'),
      'type' => MENU_LOCAL_TASK,
    );
*/

  $user_pages = array('blog' => 'blog_post', 'articles' => 'article', 'master-classes' => 'master_class', 'albums' => 'album');
  foreach ($user_pages as $url_part => $content_type) {
    $items['user/%user/' . $url_part] = array( 
      'title' => t("User's $url_part"),
      'title callback' => 'park_user_getUserTabTitle',
      'title arguments' => array(1, $url_part),
      'page callback' => 'park_user_getUserContent',
      'page arguments' => array(1, $url_part, $content_type),
      //'access callback' => 'guestbook_menu_access_user_guestbook',
      //'access arguments' => array(1, 'access user guestbooks'),
      'access arguments' => array('access content'),
      'type' => MENU_LOCAL_TASK,
    );
  }
    
  return $items;
  
}


/**
 * Returns user's content.
 */
function park_user_hcNotifyGet_ajax() {
   $status = TRUE;
  //$output = 'gv_misc_testPage_requestTest()----';
  
  $post = array();
  foreach ($_POST as $key => $value) {
    $post[$key] = check_plain(strip_tags($value));
  }
  
  global $language;
  $params['hcNotify_data'] = $post;

  drupal_mail('park_user', 'hcNotify_data', 'all4senses@gmail.com', $language->language, $params);

  drupal_json_output(array('status' => $status, /*'data' => $output, 'post' => $_POST, 'token' => $post['token'], 'test_token' => $test_token, 'valid_token' => $valid_token, 'letter' => $letter*/));
}


/**
 * Implements hook_mail().
 */
function park_user_mail($key, &$message, $params) {
  switch ($key) {
    case 'hcNotify_data':

        foreach ($params['hcNotify_data'] as $k => $value) {
          if ($k == 'data') {
            $notify[$k] = json_decode(urldecode(str_replace('%26quot%3B', '%22', urlencode($value))));
          }
          else {
            $notify[$k] = $value;
          }
        }
 
      $message['subject'] = t('HC comments notify');
      $message['body'][] = serialize($notify); //$string;
      break;
  }
  
}  


/**
 * Returns user's content.
 */
function park_user_getUserTabTitle($account, $content_title){
  return t("@name's " . $content_title, array('@name' => format_username($account)));
}


/**
 * Returns user's content.
 */
function park_user_getUserContent($account, $content_title, $content_type){
  
  $preface = NULL;
  
  // Get specific user page preface by a preface key.
  $field_prefaces_ids = field_get_items('user', $account, 'field_prefaces_collection');
  foreach ($field_prefaces_ids as $field_prefaces_id) {
    $field_collection = field_collection_field_get_entity($field_prefaces_id);
    // Almost the same.
    //$field_collection = field_collection_item_load($field_prefaces_id['value']);
    //$prefaces[] = $field_collection->view();
    if ($field_collection->field_preface_key_user['und'][0]['value'] == $content_type) {
      $preface = render($field_collection->view());
      break;
    }
  }
  
  // An other method, does the same.
  /*
  $wrapper = entity_metadata_wrapper('user', $account);
  foreach ($wrapper->field_prefaces_collection as $field_collection){
    //$prefaces[] = array('field_collection' => $field_collection->view(), 'field_collection_rendered' => render($field_collection), 'key' => $field_collection->field_preface_key_user->value());
    if ($i->field_preface_key_user->value() == $content_type) {
      $preface = render($field_collection->view());
      break;
    }
  }
  */
  
  
  
  drupal_set_title($title = t("@name's " . $content_title, array('@name' => format_username($account))), PASS_THROUGH);
  $user_content = park_pages_getContentFeedWithControls($content_type, $account->uid);
  
  // It a preface is defined, don't show the title (using preface's one).
  return ($preface ? $preface : '<h1>' . $title . '</h1>') . $user_content;
}


/**
 * Implements hook_user_view().
 */
/*
function park_user_user_view($account, $view_mode, $langcode) {
    
//  $park_user_mode = variable_get('park_user_mode', park_user_SITE_park_user | park_user_USER_park_userS);
//  if ($park_user_mode & park_user_USER_park_userS) {
//    if (user_access('access user park_users') && empty($account->data['park_user_status'])) {
//      $title = t("Read @username's park_user.", array('@username' => $account->name));
//      $link  = l(t('View recent park_user entries'), "user/$account->uid/park_user", array('attributes' => array('title' => $title)));
   

    
    
// Append guestbook on user profile page    
    
    
// TODO: makeown guestbook for each user (on demand?) on user create or by link
$gbook = node_load(4);
$gbook_comments = comment_node_page_additions($gbook); 
////dpm($gbook_comments); //dpm($gbook);

$gbook = node_view($gbook);
unset($gbook['links']['comment']); // remove link "add new comment as we have a form below"
      $account->content['park_guestbook'] = array(
        '#type' => 'user_profile_item',
        '#title' => t('The Wall'),
        '#markup' => render($gbook) . render($gbook_comments['comment_form']) . render($gbook_comments['comments']),
        //'#attributes' => array('class' => 'park_user'),
        '#weight' => 10,
      );

}
*/




/**
 * Implements hook_form_FORM_ID_alter().
 */
/*
function park_user_form_user_register_form_alter(&$form, &$form_state) {
    
  // Set up the right nickname (username) for user registered via loginza
  // !!!!!!!!!!!!!!!!!!!!!  MUST have weight bigger then loginza in a system table
    
  if (isset($_SESSION['loginza']['data'])) 
  {
    $data = $_SESSION['loginza']['data'];

    //if($data['email'])
    //   $form['account']['name']['#default_value'] = $data['email'];
    //else
        $form['account']['name']['#default_value'] = strtolower(str_replace(' ', '.', $data['name']['full_name'])); //_loginza_username($data);
        //
    //if (!empty($data['email'])) $form['account']['mail']['#default_value'] = $data['email'];
 }

}
*/


/**
 * Implements hook_user_presave().
 */
/*
function park_user_user_presave(&$edit, $account, $category) {
  foreach (array('park_user_status', 'park_user_send_email', 'park_user_intro') as $key) {
    if (isset($edit[$key])) {
      $edit['data'][$key] = $edit[$key];
    }
  }
}
*/

/**
 * Implements hook_user_delete().
 */
/*
function park_user_user_delete($account) {
  db_delete('park_user')
    ->condition('recipient', $account->uid)
    ->execute();
}
*/


/**
 * Implementation of hook_permission().
 */
/*
function park_user_permission() {
  return array(
    'moderate all park_users' => array(
      'title' => t('Moderate all park_users'),
    ),
    'moderate own park_user' => array(
      'title' => t('Moderate own park_user'),
    ),
    'access site park_user' => array(
      'title' => t('View site park_user'),
    ),
    'access user park_users' => array(
      'title' => t('View user park_users'),
    ),
    'post in site park_user' => array(
      'title' => t('Post in site park_user'),
    ),
    'post in user park_users' => array(
      'title' => t('Post in user park_users'),
    ),
  );
}
*/
